[project]
name = "diamir-assignment"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "google-genai>=1.16.1",
    "pydantic-ai>=0.2.11",
    "sqlmodel>=0.0.24",
]
